style: Silence Clippy's complaint on nightly toolchain
Clippy, with the nightly toolchain, complains as follows:

     error: this `if` statement can be collapsed
      --> cli/bin/completions.rs:75:17
       |
    75 | /                 if let Some((arg_side, value_side)) = word.split_once("=") {
    76 | |                     if let Some(arg) = node.find_arg(arg_side) {
    77 | |                         // if left side of = is arg and it has choices, offer them
    78 | |                         if !arg.choices.is_empty() {
    ...  |
    90 | |                 }
       | |_________________^
       |
       = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#collapsible_if
       = note: `-D clippy::collapsible-if` implied by `-D warnings`
       = help: to override `-D warnings` add `#[allow(clippy::collapsible_if)]`
    help: collapse nested if block
       |
    75 ~                 if let Some((arg_side, value_side)) = word.split_once("=")
    76 ~                     && let Some(arg) = node.find_arg(arg_side) {
    77 |                         // if left side of = is arg and it has choices, offer them
    ...
    88 |                         }
    89 ~                     }
       |

However, applying the suggested fix leads to compiler errors with the
stable toolchain:

     error[E0658]: `let` expressions in this position are unstable
      --> cli/bin/completions.rs:75:20
       |
    75 |                 if let Some((arg_side, value_side)) = word.split_once("=")
       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

    error[E0658]: `let` expressions in this position are unstable
      --> cli/bin/completions.rs:76:24
       |
    76 |                     && let Some(arg) = node.find_arg(arg_side)
       |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `dataplane-cli` (bin "cli" test) due to 2 previous errors

This is apparently better supported in beta and nightly, but not in the
stable version just yet. Just silence the warning for now.

Same happens at a few other locations.

We should remove the macros and "collapse" the "if"s once we have
switched to Rust v1.88 as stable.

Signed-off-by: Quentin Monnet <qmo@qmon.net>